# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoGallery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoGallery
  pod 'Alamofire', '~> 4.8.2'
  pod 'SwiftyJSON', '~> 5.0.0'
  
  target 'PhotoGalleryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoGalleryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
